import { describe, expect, it } from 'vitest';
import { generateBlockTypes } from '../blockTypes';
import type { BlockDefinition, BlockField } from '../types';

function block(apiId: string, fields: BlockField[]): BlockDefinition {
  return { apiId, name: apiId, version: 1, fields };
}

describe('generateBlockTypes', () => {
  it('starts with the "do not edit" generated header', () => {
    const output = generateBlockTypes([]);
    expect(output.startsWith('// generated by @eldrajs/vite-plugin-theme — do not edit\n')).toBe(
      true
    );
  });

  it('makes a required string field non-optional', () => {
    const output = generateBlockTypes([
      block('hero', [
        { fieldId: 'heading', name: 'Heading', type: 'string', validators: { required: true } },
      ]),
    ]);
    expect(output).toContain('heading: string;');
  });

  it('makes an optional text field optional', () => {
    const output = generateBlockTypes([
      block('hero', [{ fieldId: 'subheading', name: 'Subheading', type: 'text' }]),
    ]);
    expect(output).toContain('subheading?: string;');
  });

  it('maps every string-like field type to string', () => {
    const stringLike = [
      'string',
      'text',
      'markdown',
      'slug',
      'uuid',
      'color',
      'icon',
      'tabler-icon',
      'lucide-icon',
      'datetime',
    ];
    const output = generateBlockTypes([
      block(
        'kitchen-sink',
        stringLike.map((type) => ({ fieldId: `f_${type.replace(/-/g, '_')}`, name: type, type }))
      ),
    ]);
    for (const type of stringLike) {
      expect(output).toContain(`f_${type.replace(/-/g, '_')}?: string;`);
    }
  });

  it('maps bool to boolean', () => {
    const output = generateBlockTypes([
      block('image', [{ fieldId: 'fullWidth', name: 'Full width', type: 'bool' }]),
    ]);
    expect(output).toContain('fullWidth?: boolean;');
  });

  it('maps int and float to number', () => {
    const output = generateBlockTypes([
      block('stats', [
        { fieldId: 'count', name: 'Count', type: 'int' },
        { fieldId: 'ratio', name: 'Ratio', type: 'float' },
      ]),
    ]);
    expect(output).toContain('count?: number;');
    expect(output).toContain('ratio?: number;');
  });

  it('maps a select field to a union of its declared options', () => {
    const output = generateBlockTypes([
      block('cta', [
        {
          fieldId: 'variant',
          name: 'Variant',
          type: 'select',
          metadata: { options: ['a', 'b'] },
        },
      ]),
    ]);
    expect(output).toContain(`variant?: 'a' | 'b';`);
  });

  it('falls back a select field with no declared options to string', () => {
    const output = generateBlockTypes([
      block('cta', [{ fieldId: 'variant', name: 'Variant', type: 'select' }]),
    ]);
    expect(output).toContain('variant?: string;');
  });

  it('maps a single media field to EldraMedia', () => {
    const output = generateBlockTypes([
      block('hero', [
        { fieldId: 'image', name: 'Image', type: 'media', metadata: { multiple: false } },
      ]),
    ]);
    expect(output).toContain('image?: EldraMedia;');
  });

  it('maps a metadata.multiple media field to EldraMedia[]', () => {
    const output = generateBlockTypes([
      block('gallery', [
        { fieldId: 'images', name: 'Images', type: 'media', metadata: { multiple: true } },
      ]),
    ]);
    expect(output).toContain('images?: EldraMedia[];');
  });

  it('declares the EldraMedia interface with the framing/dimension fields', () => {
    const output = generateBlockTypes([]);
    expect(output).toContain(
      [
        'interface EldraMedia {',
        '    assetId: string;',
        '    url: string;',
        '    altText?: string;',
        '    width?: number;',
        '    height?: number;',
        '    framing?: ImageFraming;',
        '  }',
      ].join('\n')
    );
  });

  it('maps rich-text to RichTextNode and imports it only then', () => {
    const withRichText = generateBlockTypes([
      block('article', [
        { fieldId: 'body', name: 'Body', type: 'rich-text', validators: { required: true } },
      ]),
    ]);
    expect(withRichText).toContain('body: RichTextNode;');
    expect(withRichText).toContain(
      "import type { ImageFraming, RichTextNode } from '@eldrajs/theme-core';"
    );

    const withoutRichText = generateBlockTypes([block('hero', [])]);
    expect(withoutRichText).not.toContain('RichTextNode');
    expect(withoutRichText).toContain("import type { ImageFraming } from '@eldrajs/theme-core';");
  });

  it('expands a list field into Array<{ … }> from its composite item fields', () => {
    const output = generateBlockTypes([
      block('feature-grid', [
        {
          fieldId: 'features',
          name: 'Features',
          type: 'list',
          metadata: {
            item: {
              fieldId: 'feature',
              name: 'Feature',
              type: 'composite',
              metadata: {
                fields: [
                  { fieldId: 'icon', name: 'Icon', type: 'tabler-icon' },
                  {
                    fieldId: 'title',
                    name: 'Title',
                    type: 'string',
                    validators: { required: true },
                  },
                  { fieldId: 'description', name: 'Description', type: 'text' },
                ],
              },
            },
          },
        },
      ]),
    ]);
    expect(output).toContain(
      'features?: Array<{ icon?: string; title: string; description?: string }>;'
    );
  });

  it('maps unknown, composite, json, styling, seo and reference to Record<string, unknown>', () => {
    const types = ['composite', 'json', 'styling', 'seo', 'reference', 'something-unknown'];
    const output = generateBlockTypes([
      block(
        'misc',
        types.map((type) => ({ fieldId: `f_${type.replace(/-/g, '_')}`, name: type, type }))
      ),
    ]);
    for (const type of types) {
      expect(output).toContain(`f_${type.replace(/-/g, '_')}?: Record<string, unknown>;`);
    }
  });

  it('quotes a hyphenated apiId, which is not a valid bare identifier', () => {
    const output = generateBlockTypes([
      block('feature-grid', [{ fieldId: 'heading', name: 'Heading', type: 'string' }]),
    ]);
    expect(output).toContain(`'feature-grid': {`);
    expect(output).not.toContain('feature-grid: {');
  });

  it('produces two keys for two blocks', () => {
    const output = generateBlockTypes([
      block('hero', [{ fieldId: 'heading', name: 'Heading', type: 'string' }]),
      block('cta', [{ fieldId: 'heading', name: 'Heading', type: 'string' }]),
    ]);
    expect(output).toContain('hero: {');
    expect(output).toContain('cta: {');
  });

  it('is deterministic: blocks sorted by apiId, fields kept in declaration order', () => {
    const first = generateBlockTypes([
      block('zeta', [
        { fieldId: 'second', name: 'Second', type: 'string' },
        { fieldId: 'first', name: 'First', type: 'string' },
      ]),
      block('alpha', [{ fieldId: 'heading', name: 'Heading', type: 'string' }]),
    ]);
    const second = generateBlockTypes([
      block('alpha', [{ fieldId: 'heading', name: 'Heading', type: 'string' }]),
      block('zeta', [
        { fieldId: 'second', name: 'Second', type: 'string' },
        { fieldId: 'first', name: 'First', type: 'string' },
      ]),
    ]);
    expect(first).toBe(second);
    expect(first.indexOf('alpha: {')).toBeLessThan(first.indexOf('zeta: {'));
    const zetaBlock = first.slice(first.indexOf('zeta: {'));
    expect(zetaBlock.indexOf('second?: string;')).toBeLessThan(
      zetaBlock.indexOf('first?: string;')
    );
  });

  it('declares EldraBlockEntry keyed by EldraBlockData', () => {
    const output = generateBlockTypes([block('hero', [])]);
    expect(output).toContain('type EldraBlockEntry<K extends keyof EldraBlockData> = {');
    expect(output).toContain('id: string;');
    expect(output).toContain('data: EldraBlockData[K];');
  });

  it('produces an empty EldraBlockData interface for no blocks', () => {
    const output = generateBlockTypes([]);
    expect(output).toContain('interface EldraBlockData {}');
  });

  describe('reference fields', () => {
    function referenceField(relation: BlockField['relation']): BlockField {
      return { fieldId: 'source', name: 'Source', type: 'reference', relation };
    }

    it('declares EldraCollectionReference with only id and _type guaranteed', () => {
      const output = generateBlockTypes([]);
      expect(output).toContain('interface EldraCollectionReference {');
      expect(output).toContain('id: string;');
      expect(output).toContain("_type: 'collection';");
      for (const optional of [
        'slug?: string;',
        'status?: string;',
        'type?: string;',
        'productCount?: number;',
        'translations?: unknown;',
      ]) {
        expect(output).toContain(optional);
      }
      // No `publishedAt`: the resolved read carries exactly the fields Core's
      // internal collection lookup returns, and that is not one of them.
      expect(output).not.toContain('publishedAt');
    });

    it('types a collections-only single reference as EldraCollectionReference | null', () => {
      const output = generateBlockTypes([
        block('product-carousel', [referenceField({ allowCollections: true })]),
      ]);
      expect(output).toContain('source?: EldraCollectionReference | null;');
    });

    it('types a collections-only multiple reference as an array', () => {
      const output = generateBlockTypes([
        block('product-carousel', [referenceField({ allowCollections: true, multiple: true })]),
      ]);
      expect(output).toContain('source?: EldraCollectionReference[];');
    });

    it('makes a required collection reference non-optional', () => {
      const output = generateBlockTypes([
        block('product-carousel', [
          {
            ...referenceField({ allowCollections: true }),
            validators: { required: true },
          },
        ]),
      ]);
      expect(output).toContain('source: EldraCollectionReference | null;');
    });

    it.each([
      ['products as well', { allowCollections: true, allowProducts: true }],
      ['entries as well', { allowCollections: true, allowedTagIds: ['article'] }],
      ['products only', { allowProducts: true }],
      ['entries only', { allowedTagIds: ['article'] }],
    ])('keeps Record<string, unknown> for a relation allowing %s', (_label, relation) => {
      const output = generateBlockTypes([block('product-carousel', [referenceField(relation)])]);
      expect(output).toContain('source?: Record<string, unknown>;');
      expect(output).not.toContain('source?: EldraCollectionReference');
    });

    it('keeps Record<string, unknown> for a reference with no relation at all', () => {
      const output = generateBlockTypes([
        block('product-carousel', [{ fieldId: 'source', name: 'Source', type: 'reference' }]),
      ]);
      expect(output).toContain('source?: Record<string, unknown>;');
    });
  });
  describe('link fields', () => {
    it('types a bare link field as EldraLink and declares the interface once', () => {
      const output = generateBlockTypes([
        block('navigation', [{ fieldId: 'cta', name: 'Button link', type: 'link' }]),
      ]);
      expect(output).toContain('cta?: EldraLink;');
      expect(output).toContain('interface EldraLink {');
      expect(output).toContain(
        "kind: 'product' | 'collection' | 'category' | 'entry' | 'page' | 'url';"
      );
      expect(output).toContain('children?: EldraLink[];');
      expect(output.match(/interface EldraLink \{/g)).toHaveLength(1);
    });

    it('declares the interface only when some block actually uses the type', () => {
      const output = generateBlockTypes([
        block('hero', [{ fieldId: 'heading', name: 'Heading', type: 'string' }]),
      ]);
      expect(output).not.toContain('EldraLink');
    });

    it("types a list of links as an array, from the list's item", () => {
      const output = generateBlockTypes([
        block('navigation', [
          {
            fieldId: 'links',
            name: 'Links',
            type: 'list',
            metadata: { item: { fieldId: 'link', name: 'Link', type: 'link' } },
          },
        ]),
      ]);
      expect(output).toContain('links?: Array<EldraLink>;');
      expect(output).toContain('interface EldraLink {');
    });

    it('types a link nested inside a composite, and still declares the interface', () => {
      const output = generateBlockTypes([
        block('cta-band', [
          {
            fieldId: 'items',
            name: 'Items',
            type: 'list',
            metadata: {
              item: {
                fieldId: 'item',
                name: 'Item',
                type: 'composite',
                metadata: {
                  fields: [
                    { fieldId: 'label', name: 'Label', type: 'string' },
                    { fieldId: 'destination', name: 'Destination', type: 'link' },
                  ],
                },
              },
            },
          },
        ]),
      ]);
      expect(output).toContain('items?: Array<{ label?: string; destination?: EldraLink }>;');
      expect(output).toContain('interface EldraLink {');
    });
  });
});
