import { oxfmtConfig, type OxfmtConfig } from '@nokkvireyr/vue-config/oxc';

export default oxfmtConfig({
  ignorePatterns: [
    // Verbatim design source, regenerated upstream: reformatting it churns 2,500 lines and
    // makes the next drop-in impossible to diff.
    'eldra-starter-spec/**',
    // Generated by packages/ui/scripts/build-tokens.mjs; `check:tokens` compares byte for byte.
    'packages/ui/src/styles/tokens.css',
    '**/CHANGELOG.md',
    '**/RELEASE-NOTES.md',
    'packages/sdk/src/__tests__/fixtures/contract.ts',
    'packages/sdk/src/__tests__/fixtures/web-gateway.json',
    '**/.eldra/manifest.json',
    '**/.eldra/previews.json',
    '**/.eldra/block-types.d.ts',
    'examples/starter-nuxt/stories/generated/**',
  ],
}) as OxfmtConfig;
