// generated by @eldrajs/vite-plugin-theme — do not edit

import type { ImageFraming, RichTextNode } from '@eldrajs/theme-core';

declare global {
  interface EldraMedia {
    assetId: string;
    url: string;
    altText?: string;
    width?: number;
    height?: number;
    framing?: ImageFraming;
  }

  interface EldraBlockData {
    'announcement-bar': {
      variant: 'primary' | 'accent' | 'subtle';
      message: string;
      linkLabel?: string;
      linkHref?: string;
      dismissable?: boolean;
    };
    article: {
      heading: string;
      meta?: string;
      lead?: string;
      body: RichTextNode;
      width?: 'narrow' | 'content';
    };
    breadcrumbs: {
      showHome?: boolean;
      homeLabel?: string;
      trail?: Array<{ label: string; href: string }>;
      currentTitle?: string;
      showCurrent?: boolean;
      container?: 'wide' | 'content';
    };
    cta: {
      heading: string;
      body?: string;
      buttonLabel: string;
      buttonHref: string;
      secondaryButtonLabel?: string;
      secondaryButtonHref?: string;
      variant?: 'primary' | 'subtle' | 'split';
    };
    faq: {
      heading: string;
      intro?: string;
      single?: boolean;
      items?: Array<{ question: string; answer: RichTextNode }>;
    };
    'feature-grid': {
      heading: string;
      intro?: string;
      columns?: '2' | '3' | '4';
      variant?: 'cards' | 'plain';
      items?: Array<{ icon?: string; image?: EldraMedia; title: string; body?: string; href?: string }>;
    };
    footer: {
      variant: 'default' | 'minimal';
      background?: 'surface-strong' | 'primary';
      brandText: string;
      brandLogo?: EldraMedia;
      description?: string;
      groups?: Array<{ title: string; links: Array<{ label: string; href: string }> }>;
      links?: Array<{ label: string; href: string }>;
      showNewsletter?: boolean;
      newsletterTitle?: string;
      newsletterText?: string;
      social?: Array<{ network: 'instagram' | 'facebook' | 'pinterest' | 'tiktok' | 'youtube'; href: string }>;
      legalText?: string;
      legalLinks?: Array<{ label: string; href: string }>;
      showLocale?: boolean;
      showCurrency?: boolean;
    };
    gallery: {
      heading?: string;
      variant?: 'grid' | 'masonry' | 'carousel';
      images?: EldraMedia[];
      lightbox?: boolean;
    };
    hero: {
      eyebrow?: string;
      heading: string;
      subheading?: string;
      image?: EldraMedia;
      variant?: 'image-right' | 'image-background' | 'centered';
      ctaLabel?: string;
      ctaHref?: string;
      secondaryCtaLabel?: string;
      secondaryCtaHref?: string;
    };
    image: {
      image?: EldraMedia;
      caption?: string;
      aspect?: 'auto' | '16/9' | '4/3' | '1/1' | '3/4';
      width?: 'narrow' | 'content' | 'wide' | 'full';
    };
    navigation: {
      variant: 'default' | 'centered' | 'minimal';
      brandText: string;
      brandLogo?: EldraMedia;
      links?: Array<{ label: string; href?: string; menuLinks?: Array<{ group?: string; label: string; href: string }>; features?: Array<{ image?: EldraMedia; label: string; href: string }> }>;
      showSearch?: boolean;
      searchStyle?: 'icon' | 'field' | 'inline';
      showAccount?: boolean;
      ctaLabel?: string;
      ctaHref?: string;
      sticky?: boolean;
      transparentOverHero?: boolean;
    };
    testimonials: {
      heading: string;
      variant?: 'grid' | 'carousel';
      items?: Array<{ quote: string; author: string; role?: string; avatar?: EldraMedia; rating?: number }>;
    };
  }

  type EldraBlockEntry<K extends keyof EldraBlockData> = {
    id: string;
    data: EldraBlockData[K];
  };
}

export {};
