// generated by @eldrajs/vite-plugin-theme — do not edit

import type { ImageFraming, RichTextNode } from '@eldrajs/theme-core';

declare global {
  interface EldraMedia {
    assetId: string;
    url: string;
    altText?: string;
    width?: number;
    height?: number;
    framing?: ImageFraming;
  }

  interface EldraBlockData {
    'announcement-bar': {
      variant: 'primary' | 'accent' | 'subtle';
      message: string;
      linkLabel?: string;
      linkHref?: string;
      dismissable?: boolean;
    };
    article: {
      heading: string;
      meta?: string;
      lead?: string;
      body: RichTextNode;
      width?: 'narrow' | 'content';
    };
    breadcrumbs: {
      showHome?: boolean;
      homeLabel?: string;
      trail?: Array<{ label: string; href: string }>;
      currentTitle?: string;
      showCurrent?: boolean;
      container?: 'wide' | 'content';
    };
    contact: {
      variant: 'split' | 'details-only' | 'form-only';
      heading: string;
      hideHeading?: boolean;
      intro?: string;
      address?: string;
      hours?: Array<{ days: string; time: string }>;
      phone?: string;
      email?: string;
      mapLinkLabel?: string;
      mapLinkHref?: string;
      mapEmbed?: string;
      mapImage?: EldraMedia;
      mapNote?: string;
      formTitle?: string;
      topics?: Array<{ label: string }>;
      showOrderNumber?: boolean;
      recipient: string;
      successText?: string;
    };
    cta: {
      variant: 'primary' | 'subtle' | 'split' | 'banner';
      eyebrow?: string;
      heading: string;
      text?: string;
      primaryCtaLabel: string;
      primaryCtaHref: string;
      secondaryCtaLabel?: string;
      secondaryCtaHref?: string;
      image?: EldraMedia;
    };
    faq: {
      variant: 'one-column' | 'two-column';
      heading: string;
      intro?: string;
      exclusive?: boolean;
      items: Array<{ question: string; answer: RichTextNode; open?: boolean }>;
      contactText?: string;
      contactLinkLabel?: string;
      contactLinkHref?: string;
      sectionBackground?: 'none' | 'surface' | 'surface-strong';
    };
    'feature-grid': {
      variant: 'cards' | 'plain';
      heading?: string;
      intro?: string;
      headLinkLabel?: string;
      headLinkHref?: string;
      columns: '2' | '3' | '4';
      mediaType: 'icon' | 'image';
      items: Array<{ icon?: string; image?: EldraMedia; title: string; text?: string; linkLabel?: string; href?: string }>;
    };
    footer: {
      variant: 'default' | 'minimal';
      background?: 'surface-strong' | 'primary';
      brandText: string;
      brandLogo?: EldraMedia;
      description?: string;
      groups?: Array<{ title: string; links: Array<{ label: string; href: string }> }>;
      links?: Array<{ label: string; href: string }>;
      showNewsletter?: boolean;
      newsletterTitle?: string;
      newsletterText?: string;
      social?: Array<{ network: 'instagram' | 'facebook' | 'pinterest' | 'tiktok' | 'youtube'; href: string }>;
      legalText?: string;
      legalLinks?: Array<{ label: string; href: string }>;
      showLocale?: boolean;
      showCurrency?: boolean;
    };
    gallery: {
      heading?: string;
      variant?: 'grid' | 'masonry' | 'carousel';
      images?: EldraMedia[];
      lightbox?: boolean;
    };
    hero: {
      variant: 'image-right' | 'image-left' | 'image-background' | 'centered' | 'split-carousel';
      eyebrow?: string;
      heading: string;
      subheading?: string;
      image?: EldraMedia;
      slides?: Array<{ image: EldraMedia; alt: string; linkLabel?: string; href?: string }>;
      spacing?: 'md' | 'sm' | 'lg';
      primaryCtaLabel?: string;
      primaryCtaHref?: string;
      secondaryCtaLabel?: string;
      secondaryCtaHref?: string;
    };
    image: {
      image?: EldraMedia;
      caption?: string;
      aspect?: 'auto' | '16/9' | '4/3' | '1/1' | '3/4';
      width?: 'narrow' | 'content' | 'wide' | 'full';
    };
    navigation: {
      variant: 'default' | 'centered' | 'minimal';
      brandText: string;
      brandLogo?: EldraMedia;
      links?: Array<{ label: string; href?: string; menuLinks?: Array<{ group?: string; label: string; href: string }>; features?: Array<{ image?: EldraMedia; label: string; href: string }> }>;
      showSearch?: boolean;
      searchStyle?: 'icon' | 'field' | 'inline';
      showAccount?: boolean;
      ctaLabel?: string;
      ctaHref?: string;
      sticky?: boolean;
      transparentOverHero?: boolean;
    };
    newsletter: {
      variant: 'centered' | 'split';
      heading: string;
      text?: string;
      fieldLabel?: string;
      placeholder?: string;
      buttonLabel?: string;
      consent: RichTextNode;
      requireConsentCheckbox?: boolean;
      consentCheckboxLabel?: string;
      successTitle?: string;
      successText?: string;
      list: string;
      sectionBackground?: 'none' | 'surface' | 'surface-strong' | 'primary' | 'accent';
    };
    'pricing-table': {
      heading: string;
      intro?: string;
      featureRows: Array<{ label: string }>;
      plans: Array<{ name: string; description?: string; price: string; period: string; note?: string; ctaLabel: string; ctaHref: string; included: Array<boolean> }>;
      highlightedPlan?: string;
      highlightLabel?: string;
      footnote?: string;
      sectionBackground?: 'none' | 'surface' | 'surface-strong';
    };
    'split-content': {
      startWith: 'image-left' | 'image-right';
      rows: Array<{ image?: EldraMedia; eyebrow?: string; heading: string; text?: RichTextNode; linkLabel?: string; href?: string }>;
    };
    stats: {
      variant: 'row' | 'split';
      heading: string;
      intro?: string;
      items: Array<{ value: string; label: string }>;
      sectionBackground?: 'none' | 'surface' | 'surface-strong' | 'primary' | 'accent';
    };
    team: {
      heading: string;
      intro?: string;
      linkLabel?: string;
      linkHref?: string;
      people: Array<{ photo?: EldraMedia; name: string; role: string; bio?: string; links?: Array<{ type: 'instagram' | 'email' | 'website' | 'tiktok' | 'pinterest'; href: string }> }>;
      sectionBackground?: 'none' | 'surface' | 'surface-strong';
    };
    testimonials: {
      variant: 'grid' | 'carousel' | 'single-large';
      heading: string;
      summary?: string;
      linkLabel?: string;
      linkHref?: string;
      items: Array<{ quote: string; name: string; meta?: string; avatar?: EldraMedia; rating?: 'none' | '1' | '2' | '3' | '4' | '5'; productLabel?: string; productHref?: string }>;
      sectionBackground?: 'none' | 'surface' | 'surface-strong' | 'primary';
    };
    timeline: {
      variant: 'steps' | 'history';
      heading: string;
      intro?: string;
      linkLabel?: string;
      linkHref?: string;
      items: Array<{ year?: string; title: string; text?: string }>;
      columns?: 'auto' | '3' | '4' | '5';
      sectionBackground?: 'none' | 'surface' | 'surface-strong';
    };
    'video-embed': {
      variant: 'contained' | 'split';
      heading?: string;
      intro?: string;
      videoUrl: string;
      videoTitle: string;
      duration?: string;
      poster?: EldraMedia;
      caption?: string;
      transcriptLabel?: string;
      transcriptHref?: string;
      privacyNote?: string;
      sectionBackground?: 'none' | 'surface' | 'surface-strong' | 'primary';
    };
  }

  type EldraBlockEntry<K extends keyof EldraBlockData> = {
    id: string;
    data: EldraBlockData[K];
  };
}

export {};
