#!/usr/bin/env node
// Generates one CSF3 story file per block under `stories/generated/`, from
// `blocks/*/block.json` and `blocks/*/mock.json`.
//
// Storybook's story index needs one real `export default` (component meta)
// per file, and the story id it derives is `<kebab(title)>--<kebab(export
// name)>`. To get the exact `blocks-<apiId>--default` id `previews.mjs`
// navigates to, every block gets its own generated file titled
// `Blocks/<apiId>` — a single shared file (one `Blocks` title for every
// block) cannot produce a per-block id namespace without either duplicate
// default exports (invalid CSF) or per-story id overrides Storybook does not
// support. This is the one deliberate deviation from the brief's literal
// `stories/blocks.generated.stories.ts` filename; see task-2-report.md.
//
// Re-run by `storybook dev`/`build-storybook` (via `.storybook/main.ts`'s
// `viteFinal`) so the generated files are always current; also runnable
// directly (`node scripts/generate-stories.mjs`).
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const defaultRootDir = join(scriptDir, '..');

/**
 * @param {{ rootDir?: string }} [options]
 * @returns {string[]} the block apiIds a story file was generated for
 */
export function generateStories(options = {}) {
  const rootDir = options.rootDir ?? defaultRootDir;
  const blocksDir = join(rootDir, 'blocks');
  const outDir = join(rootDir, 'stories', 'generated');
  mkdirSync(outDir, { recursive: true });

  const apiIds = existsSync(blocksDir)
    ? readdirSync(blocksDir, { withFileTypes: true })
        .filter((entry) => entry.isDirectory())
        .map((entry) => entry.name)
        .filter((apiId) => existsSync(join(blocksDir, apiId, 'block.json')))
        .sort()
    : [];

  const writtenFiles = new Set();
  for (const apiId of apiIds) {
    const blockDir = join(blocksDir, apiId);
    const block = JSON.parse(readFileSync(join(blockDir, 'block.json'), 'utf8'));
    const hasPreview = existsSync(join(blockDir, 'preview.json'));
    const fileName = `${apiId}.stories.ts`;
    const importPath = relative(outDir, blockDir).split('\\').join('/');
    writeFileSync(join(outDir, fileName), renderStoryFile(apiId, block, importPath, hasPreview));
    writtenFiles.add(fileName);
  }

  // Drop generated files for blocks that no longer exist, so a removed or
  // renamed block does not leave a stale story behind.
  for (const entry of readdirSync(outDir)) {
    if (entry.endsWith('.stories.ts') && !writtenFiles.has(entry)) {
      rmSync(join(outDir, entry));
    }
  }

  return apiIds;
}

function pascalCase(value) {
  return String(value)
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
}

/** Top-level `select` fields with static string options get one extra story per option. */
function selectVariants(block) {
  const fields = Array.isArray(block.fields) ? block.fields : [];
  const variants = [];
  for (const field of fields) {
    if (field?.type !== 'select') continue;
    const options = field?.metadata?.options;
    if (!Array.isArray(options)) continue;
    for (const option of options) {
      if (typeof option !== 'string') continue;
      variants.push({
        exportName: `${pascalCase(field.fieldId)}${pascalCase(option)}`,
        fieldId: field.fieldId,
        option,
      });
    }
  }
  return variants;
}

function renderStoryFile(apiId, block, importPath, hasPreview) {
  // `mock.json` is exactly what Studio seeds when an author inserts the
  // block (media fields absent); `preview.json` (when present) is a
  // story/preview-only overlay of demo imagery merged on top of it. `base`
  // is what every story except `Inserted` renders from, so a block with no
  // media fields (no preview.json) is unaffected.
  const lines = [
    '// GENERATED FILE — do not edit by hand.',
    '// Regenerated by scripts/generate-stories.mjs (run automatically by',
    '// `storybook dev` / `build-storybook`, or directly with',
    '// `node scripts/generate-stories.mjs`) from blocks/*/block.json + mock.json',
    '// (+ preview.json, when the block has one).',
    "import type { Meta, StoryObj } from '@storybook/vue3-vite';",
    `import Block from '${importPath}/Block.vue';`,
    `import mock from '${importPath}/mock.json';`,
  ];
  if (hasPreview) lines.push(`import preview from '${importPath}/preview.json';`);
  lines.push(
    '',
    'const meta: Meta<typeof Block> = {',
    `  title: ${JSON.stringify(`Blocks/${apiId}`)},`,
    '  component: Block,',
    '};',
    'export default meta;',
    '',
    'type Story = StoryObj<typeof Block>;',
    '',
    hasPreview ? 'const base = { ...mock, ...preview };' : 'const base = mock;',
    '',
    'export const Default: Story = {',
    `  args: { entry: { id: ${JSON.stringify(apiId)}, data: base } },`,
    '};',
    '',
    // The bare seed Studio writes when an author inserts the block — no
    // preview overlay, so a media field is absent, never a fixture object.
    'export const Inserted: Story = {',
    `  args: { entry: { id: ${JSON.stringify(apiId)}, data: mock } },`,
    '};'
  );

  for (const { exportName, fieldId, option } of selectVariants(block)) {
    lines.push(
      '',
      `export const ${exportName}: Story = {`,
      '  args: {',
      `    entry: { id: ${JSON.stringify(apiId)}, data: { ...base, ${JSON.stringify(fieldId)}: ${JSON.stringify(option)} } },`,
      '  },',
      '};'
    );
  }

  lines.push('');
  return lines.join('\n');
}

const isMain = process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const apiIds = generateStories();
  console.log(
    `[eldra] generated ${apiIds.length} block ${apiIds.length === 1 ? 'story' : 'stories'}`
  );
}
