#!/usr/bin/env node
// tokens.json (W3C design tokens) → src/styles/tokens.css. `--check` fails when the checked-in
// file is stale; the root lint:check runs it.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '../../../eldra-starter-spec/tokens.json');
const TARGET = resolve(here, '../src/styles/tokens.css');

const ref = (value) => {
  const m = /^\{font\.family\.([\w-]+)\}$/.exec(String(value));
  return m ? `var(--eldra-font-${m[1]})` : value;
};

export function renderTokensCss(tokens) {
  const lines = [];
  const durations = [];
  const push = (name, value) => lines.push(`  --eldra-${name}: ${value};`);
  for (const [role, t] of Object.entries(tokens.color ?? {})) push(`color-${role}`, t.$value);
  for (const [name, t] of Object.entries(tokens.font?.family ?? {})) push(`font-${name}`, t.$value);
  for (const [name, t] of Object.entries(tokens.font?.style ?? {})) {
    const v = t.$value;
    push(`text-${name}-family`, ref(v.fontFamily));
    push(`text-${name}-size`, v.fontSize);
    push(`text-${name}-line`, v.lineHeight);
    push(`text-${name}-weight`, v.fontWeight);
    push(`text-${name}-tracking`, v.letterSpacing ?? '0');
  }
  for (const [name, t] of Object.entries(tokens.space ?? {})) push(name, t.$value);
  for (const [name, t] of Object.entries(tokens.radius ?? {})) push(name, t.$value);
  for (const [name, t] of Object.entries(tokens.shadow ?? {})) push(name, t.$value);
  for (const [name, t] of Object.entries(tokens.layout ?? {})) push(name, t.$value);
  for (const [name, t] of Object.entries(tokens.duration ?? {})) {
    push(name, t.$value);
    durations.push(name);
  }
  for (const [name, t] of Object.entries(tokens.easing ?? {}))
    push(name, `cubic-bezier(${t.$value.join(', ')})`);
  for (const [name, t] of Object.entries(tokens.zIndex ?? {})) push(name, t.$value);
  const reduced = durations.map((d) => `    --eldra-${d}: 0ms;`).join('\n');
  return [
    '/* Generated by scripts/build-tokens.mjs from eldra-starter-spec/tokens.json — do not edit. */',
    ':root {',
    ...lines,
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    reduced,
    '  }',
    '}',
    '',
  ].join('\n');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const css = renderTokensCss(JSON.parse(readFileSync(SOURCE, 'utf8')));
  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(TARGET, 'utf8');
    } catch {}
    if (current !== css) {
      console.error('src/styles/tokens.css is stale; run pnpm --filter @eldrajs/ui build-tokens');
      process.exit(1);
    }
  } else {
    writeFileSync(TARGET, css);
  }
}
