import type { BlockDefinition, BlockField } from './types';

/**
 * Generates `.eldra/block-types.d.ts`: a global ambient contract for every
 * block declared under `blocks/*.block.json` — `interface EldraBlockData`
 * (one property per block `apiId`, typed from its `fields`) and the
 * `EldraBlockEntry<K>` helper a `Block.vue` uses in `defineProps`. Written by
 * the Vite plugin on scan (`plugin.ts`) and by `eldra-theme types --blocks`
 * (`theme-cli`).
 *
 * Field mapping (spec §3 "Block contract"): required validators
 * (`validators.required === true`) make the TS property non-optional;
 * everything else is optional (`?`). `composite`/`json`/`styling`/`seo`/
 * `reference` — and any type this generator does not recognize — fall back
 * to `Record<string, unknown>` (typed later), except when a `composite`
 * field is a `list`'s item shape, where its declared `metadata.fields` are
 * expanded into an inline object type so `list` produces a real
 * `Array<{ … }>` rather than `Array<Record<string, unknown>>`.
 */
export function generateBlockTypes(blocks: BlockDefinition[]): string {
  const sorted = [...blocks].sort((a, b) => a.apiId.localeCompare(b.apiId));
  const usesRichText = sorted.some((block) => fieldsUseTypeDeep(block.fields ?? [], 'rich-text'));

  const typeImports = usesRichText ? 'ImageFraming, RichTextNode' : 'ImageFraming';
  const blockDataBody =
    sorted.length === 0
      ? ''
      : `\n${sorted.map((block) => `    ${propertyKey(block.apiId)}: ${blockDataType(block.fields ?? [], '    ')};`).join('\n')}\n  `;

  return `// generated by @eldrajs/vite-plugin-theme — do not edit

import type { ${typeImports} } from '@eldrajs/theme-core';

declare global {
  interface EldraMedia {
    assetId: string;
    url: string;
    altText?: string;
    width?: number;
    height?: number;
    framing?: ImageFraming;
  }

  interface EldraBlockData {${blockDataBody}}

  type EldraBlockEntry<K extends keyof EldraBlockData> = {
    id: string;
    data: EldraBlockData[K];
  };
}

export {};
`;
}

function blockDataType(fields: BlockField[], indent: string): string {
  if (fields.length === 0) return '{}';
  const lines = fields.map(
    (field) =>
      `${indent}  ${propertyKey(field.fieldId)}${isRequired(field) ? '' : '?'}: ${fieldTypeExpr(field)};`
  );
  return `{\n${lines.join('\n')}\n${indent}}`;
}

function fieldTypeExpr(field: BlockField): string {
  switch (field.type) {
    case 'string':
    case 'text':
    case 'markdown':
    case 'slug':
    case 'uuid':
    case 'color':
    case 'icon':
    case 'tabler-icon':
    case 'lucide-icon':
    case 'datetime':
      return 'string';
    case 'bool':
      return 'boolean';
    case 'int':
    case 'float':
      return 'number';
    case 'rich-text':
      return 'RichTextNode';
    case 'media':
      return isMultipleMedia(field) ? 'EldraMedia[]' : 'EldraMedia';
    case 'select':
      return selectUnion(field);
    case 'list':
      return listType(field);
    default:
      return 'Record<string, unknown>';
  }
}

function isMultipleMedia(field: BlockField): boolean {
  return isRecord(field.metadata) && field.metadata.multiple === true;
}

function selectUnion(field: BlockField): string {
  const metadata = field.metadata;
  const options = isRecord(metadata) && Array.isArray(metadata.options) ? metadata.options : [];
  const literals = options.filter((option): option is string => typeof option === 'string');
  return literals.length > 0 ? literals.map(singleQuoted).join(' | ') : 'string';
}

function singleQuoted(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function listType(field: BlockField): string {
  const item = isRecord(field.metadata) ? field.metadata.item : undefined;
  if (!isBlockFieldLike(item)) return 'unknown[]';
  return `Array<${itemTypeExpr(item)}>`;
}

/** The type of one `list` entry. A `composite` item expands its declared
 * `metadata.fields` inline instead of collapsing to `Record<string, unknown>`
 * — see the module doc comment. */
function itemTypeExpr(item: BlockField): string {
  if (item.type === 'composite') return inlineObjectType(compositeFields(item));
  return fieldTypeExpr(item);
}

function compositeFields(field: BlockField): BlockField[] {
  const metadata = field.metadata;
  const fields = isRecord(metadata) && Array.isArray(metadata.fields) ? metadata.fields : [];
  return fields.filter(isBlockFieldLike);
}

function inlineObjectType(fields: BlockField[]): string {
  if (fields.length === 0) return 'Record<string, unknown>';
  const props = fields.map(
    (field) =>
      `${propertyKey(field.fieldId)}${isRequired(field) ? '' : '?'}: ${fieldTypeExpr(field)}`
  );
  return `{ ${props.join('; ')} }`;
}

const VALID_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/** Quotes a property key when it is not a valid bare TS identifier — block
 * `apiId`s may contain hyphens (e.g. `feature-grid`), which field ids never
 * do, but this is applied uniformly for safety. */
function propertyKey(id: string): string {
  return VALID_IDENTIFIER.test(id) ? id : singleQuoted(id);
}

function isRequired(field: BlockField): boolean {
  return isRecord(field.validators) && field.validators.required === true;
}

function fieldsUseTypeDeep(fields: BlockField[], type: string): boolean {
  return fields.some((field) => fieldUsesTypeDeep(field, type));
}

function fieldUsesTypeDeep(field: BlockField, type: string): boolean {
  if (field.type === type) return true;
  if (field.type === 'list') {
    const item = isRecord(field.metadata) ? field.metadata.item : undefined;
    return isBlockFieldLike(item) && fieldUsesTypeDeep(item, type);
  }
  if (field.type === 'composite') {
    return compositeFields(field).some((child) => fieldUsesTypeDeep(child, type));
  }
  return false;
}

function isBlockFieldLike(value: unknown): value is BlockField {
  return isRecord(value) && typeof value.fieldId === 'string' && typeof value.type === 'string';
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}
