#!/usr/bin/env node
// Snapshots the public storefront contract into the SDK and generates its types.
//   node scripts/contract.mjs                    regenerate from the committed snapshot
//   node scripts/contract.mjs --from <path|url>  refresh the snapshot first
//   node scripts/contract.mjs --check            fail if the generated files are stale
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const contractDir = resolve(root, 'src/contract');
const snapshotPath = resolve(contractDir, 'web-gateway.v1.json');
const typesPath = resolve(contractDir, 'v1.ts');
const versionPath = resolve(contractDir, 'version.ts');

const args = process.argv.slice(2);
const check = args.includes('--check');
const fromIndex = args.indexOf('--from');
const from = fromIndex === -1 ? undefined : args[fromIndex + 1];

async function loadSource(source) {
  if (/^https?:\/\//.test(source)) {
    const response = await fetch(source);
    if (!response.ok) throw new Error(`fetch ${source}: ${response.status}`);
    return response.text();
  }
  return readFile(resolve(process.cwd(), source), 'utf8');
}

function normalise(json) {
  return `${JSON.stringify(JSON.parse(json), null, 2)}\n`;
}

async function generate(snapshot) {
  const spec = JSON.parse(snapshot);
  const version = spec.info?.version;
  if (typeof version !== 'string' || !version) {
    throw new Error('contract snapshot has no info.version');
  }
  const ast = await openapiTS(spec, { alphabetize: true, exportType: true });
  const header =
    `// Generated from web-gateway.v1.json (contract ${version}) by scripts/contract.mjs.\n` +
    `// Do not edit; run \`pnpm contract\`.\n\n`;
  const types = header + astToString(ast);
  const versionFile =
    `// Generated by scripts/contract.mjs; do not edit.\n` +
    `export const ELDRA_CONTRACT_VERSION = '${version}';\n`;
  return { types, versionFile };
}

async function readOrEmpty(path) {
  try {
    return await readFile(path, 'utf8');
  } catch {
    return '';
  }
}

async function main() {
  let snapshot;
  if (from) {
    snapshot = normalise(await loadSource(from));
    if (!check) await writeFile(snapshotPath, snapshot);
  } else {
    snapshot = await readFile(snapshotPath, 'utf8');
  }

  const { types, versionFile } = await generate(snapshot);

  if (check) {
    const stale = [];
    if (from && (await readOrEmpty(snapshotPath)) !== snapshot) stale.push(snapshotPath);
    if ((await readOrEmpty(typesPath)) !== types) stale.push(typesPath);
    if ((await readOrEmpty(versionPath)) !== versionFile) stale.push(versionPath);
    if (stale.length > 0) {
      console.error('Contract files are stale; run `pnpm contract` and commit:');
      for (const path of stale) console.error(`  ${path}`);
      process.exit(1);
    }
    console.log('Contract files are up to date.');
    return;
  }

  await writeFile(typesPath, types);
  await writeFile(versionPath, versionFile);
  console.log(`Contract types generated for contract ${JSON.parse(snapshot).info.version}.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
