// generated by @eldrajs/vite-plugin-theme — do not edit

import type { ImageFraming } from '@eldrajs/theme-core';

declare global {
  interface EldraMedia {
    assetId: string;
    url: string;
    altText?: string;
    width?: number;
    height?: number;
    framing?: ImageFraming;
  }

  /** A catalog collection a `reference` field points at. Only `id` and
   *  `_type` are guaranteed: the public read returns the stub at depth 0, for
   *  an archived collection, and for a draft overlay in the page builder. */
  interface EldraCollectionReference {
    id: string;
    _type: 'collection';
    slug?: string;
    status?: string;
    type?: string;
    productCount?: number;
    translations?: unknown;
  }

  interface EldraBlockData {
    cta: {
      label?: string;
    };
    hero: {
      heading?: string;
      subheading?: string;
    };
  }

  type EldraBlockEntry<K extends keyof EldraBlockData> = {
    id: string;
    data: EldraBlockData[K];
  };

  /** The theme's own message keys (`i18n/<tag>.json`'s default locale),
   *  flattened to dotted paths — vue-i18n's `t()` argument. */
  type MessageKey = 'banner.welcome';
}

export {};
