// generated by @eldrajs/vite-plugin-theme — do not edit

import type { ImageFraming } from '@eldrajs/theme-core';

declare global {
  interface EldraMedia {
    assetId: string;
    url: string;
    altText?: string;
    width?: number;
    height?: number;
    framing?: ImageFraming;
  }

  interface EldraBlockData {
    cta: {
      label?: string;
    };
    hero: {
      heading?: string;
      subheading?: string;
    };
  }

  type EldraBlockEntry<K extends keyof EldraBlockData> = {
    id: string;
    data: EldraBlockData[K];
  };
}

export {};
